// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	user3 "mono-base/cmd/http/controllers/user"
	"mono-base/internal/infrastructure/database/postgres"
	"mono-base/internal/services/user"
	user2 "mono-base/internal/usecases/user"
)

import (
	_ "mono-base/cmd/http/docs"
)

// Injectors from wire.go:

func wireApp(app *App) error {
	db := postgres.GetDBContext()
	userRepository := postgres.NewUserRepository(db)
	authService := user.NewAuthService(userRepository)
	loginUseCase := user2.NewLoginUseCase(authService, userRepository)
	controllerV1 := user3.NewUserControllerV1(loginUseCase)
	controllerV2 := user3.NewUserControllerV2(loginUseCase)
	error2 := inject(app, controllerV1, controllerV2)
	return error2
}
