// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"mono-base/internal/infrastructure/database/postgres"
	"mono-base/internal/services/user"
	user2 "mono-base/internal/usecases/user"
)

// Injectors from wire.go:

func wireApp(app *App) error {
	db := postgres.GetDBContext()
	userRepository := postgres.NewUserRepository(db)
	authService := user.NewAuthService(userRepository)
	loginUseCase := user2.NewLoginUseCase(authService, userRepository)
	error2 := inject(app, loginUseCase)
	return error2
}
